CREATE TABLE IF NOT EXISTS feeds (
  id          INTEGER PRIMARY KEY,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_fetched_at  DATETIME NULL,
  name        TEXT    NOT NULL,
  url         TEXT    NOT NULL UNIQUE,
  user_id     INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS feeds_updated_at
  AFTER UPDATE ON feeds
  FOR EACH ROW
BEGIN
  UPDATE feeds
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = OLD.id;
END;

